import { posix } from 'node:path'
import { slugify } from '@md-plugins/shared'
import type { JsonValue, SearchRecord, SearchRecordType } from './types'

const markdownExtensionRE = /\.md$/i
const whitespaceRE = /\s+/g
const htmlTagRE = /<[^>]+>/g

/**
 * Normalizes string or array glob options into a concrete pattern list.
 */
export function normalizePatterns(
  patterns: string | string[] | undefined,
  fallback: string[],
): string[] {
  if (patterns === undefined) {
    return fallback
  }

  return Array.isArray(patterns) ? patterns : [patterns]
}

/**
 * Converts a Markdown file path into the route path generated by Q-Press conventions.
 */
export function markdownFileToSearchRoutePath(
  markdownFile: string,
  landingPage = 'landing-page.md',
): string {
  const normalizedFile = markdownFile.replace(/\\/g, '/').replace(/^\.\//, '')
  const normalizedLandingPage = landingPage.replace(/\\/g, '/').replace(/^\.\//, '')

  if (normalizedFile === normalizedLandingPage) {
    return '/'
  }

  const routeParts = normalizedFile.replace(markdownExtensionRE, '').split('/')
  const lastPart = routeParts.at(-1)
  const parentPart = routeParts.at(-2)

  if (routeParts.length > 1 && lastPart === parentPart) {
    routeParts.pop()
  }

  return `/${routeParts.join('/')}`
}

function joinPathParts(parts: Array<string | undefined>): string {
  const filteredParts = parts
    .filter((part): part is string => typeof part === 'string' && part.length > 0)
    .map((part) => part.replace(/^\/+|\/+$/g, ''))
    .filter(Boolean)

  if (filteredParts.length === 0) {
    return '/'
  }

  return `/${filteredParts.join('/')}`.replace(/\/{2,}/g, '/')
}

/**
 * Joins URL path fragments without stripping protocol separators.
 */
export function joinUrlPath(...parts: Array<string | undefined>): string {
  const [base, ...rest] = parts

  if (base !== undefined && /^[a-z][a-z\d+.-]*:\/\//i.test(base)) {
    const url = new URL(base)
    const path = joinPathParts([url.pathname, ...rest])

    return `${url.origin}${path === '/' ? '' : path}`
  }

  return joinPathParts(parts)
}

/**
 * Applies Vite base and optional route base to a route path.
 */
export function createSearchUrl(
  base: string | undefined,
  routeBase: string | undefined,
  path: string,
): string {
  return joinUrlPath(base ?? '/', routeBase, path)
}

/**
 * Converts arbitrary Markdown or inline HTML text into indexable text.
 */
export function normalizeSearchText(value: unknown): string {
  return String(value ?? '')
    .replace(htmlTagRE, ' ')
    .replaceAll('|', ' ')
    .replace(whitespaceRE, ' ')
    .trim()
}

/**
 * Converts common frontmatter shapes into string tags.
 */
export function normalizeSearchTags(value: unknown): string[] {
  if (Array.isArray(value)) {
    return value.flatMap((entry) => normalizeSearchTags(entry))
  }

  if (typeof value === 'string') {
    return value
      .split(/[,\s]+/)
      .map((entry) => normalizeSearchText(entry))
      .filter(Boolean)
  }

  if (typeof value === 'number' || typeof value === 'boolean') {
    return [String(value)]
  }

  return []
}

/**
 * Creates deterministic-but-readable anchor slugs while handling duplicates.
 */
export function createUniqueAnchorFactory(): (title: string) => string {
  const seen = new Map<string, number>()

  return (title: string): string => {
    const base = slugify(title) || 'section'
    const count = seen.get(base) ?? 0
    seen.set(base, count + 1)

    return count === 0 ? base : `${base}-${count}`
  }
}

export interface CreateSearchRecordInput {
  type: SearchRecordType
  path: string
  url: string
  title: string
  content: string
  hierarchy: string[]
  tags: string[]
  source: SearchRecord['source']
  index: number
  anchor?: string
  section?: string
  meta?: Record<string, JsonValue>
}

/**
 * Creates a normalized search record with a stable id.
 */
export function createSearchRecord({
  type,
  path,
  url,
  title,
  content,
  hierarchy,
  tags,
  source,
  index,
  anchor,
  section,
  meta,
}: CreateSearchRecordInput): SearchRecord {
  const idParts = [path, anchor, type, String(index)].filter(Boolean).join('-')

  return {
    id: slugify(idParts) || `search-record-${index}`,
    type,
    title,
    content,
    url: anchor ? `${url}#${anchor}` : url,
    path,
    anchor,
    section,
    hierarchy,
    tags,
    source,
    meta,
  }
}

/**
 * Converts a relative Markdown path to a stable absolute source path.
 */
export function resolveMarkdownSourcePath(root: string, relativeFile: string): string {
  return posix.join(root.replace(/\\/g, '/'), relativeFile)
}
