name: Run Vitest Tests

on:
  push: # Trigger on push to any branch
  pull_request: # Trigger on pull request to any branch

jobs:
  vitest:
    name: Run Vitest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # Test against multiple Node.js versions

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Use Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install dependencies for all packages
      - name: Install dependencies
        run: pnpm install

      # Build all packages except docs
      - name: Build all packages (exclude docs)
        run: pnpm build --filter '!packages/docs'

      # Prepare Quasar for docs package
      - name: Prepare Quasar (docs)
        run: pnpm --filter 'packages/docs' prepare

      # Build the docs package
      - name: Build Quasar project (docs)
        run: pnpm build --filter 'packages/docs'

      # Run Vitest tests
      - name: Run Vitest tests
        run: pnpm test
