name: Run Vitest Tests

on:
  push: # Trigger on push to any branch
  pull_request: # Trigger on pull requst to any branch

jobs:
  vitest:
    name: Run Vitest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # Test against multiple Node.js versions

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Use Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run Vitest
      - name: Run Vitest tests
        run: pnpm test
