name: Run Vitest Tests

on:
  push: # Trigger on push to any branch
  pull_request: # Trigger on pull request to any branch

jobs:
  vitest:
    name: Run Vitest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20] # Test against multiple Node.js versions

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v4

      # Install pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4

      # Use Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      # Install dependencies for non-Quasar packages
      - name: Install dependencies (exclude docs)
        run: pnpm install --filter "!packages/docs"

      # Build all non-Quasar packages
      - name: Build non-Quasar packages
        run: pnpm build --filter "!packages/docs"

      # Install dependencies for Quasar docs
      - name: Install dependencies for Quasar project (docs)
        run: pnpm install --filter "packages/docs"

      # Build the Quasar project (docs)
      - name: Build Quasar project (docs)
        run: pnpm build --filter "packages/docs"

      # Run Vitest
      - name: Run Vitest tests
        run: pnpm test
